/********************************************************************************
** Form generated from reading UI file 'teamchoice.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TEAMCHOICE_H
#define UI_TEAMCHOICE_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_TeamChoice
{
public:
    QLabel *logoTeamChoice;
    QListWidget *listJ1;
    QLabel *J1J2;
    QLabel *logoJ1;
    QListWidget *listJ2;
    QLabel *logoJ2;
    QPushButton *playButton;
    QLabel *pgname1;
    QLabel *sgname1;
    QLabel *sfname1;
    QLabel *pfname1;
    QLabel *cname1;
    QLabel *crating1;
    QLabel *pfrating1;
    QLabel *crating2;
    QLabel *sfrating1;
    QLabel *pgrating1;
    QLabel *sgrating1;
    QLabel *pfrating2;
    QLabel *sfrating2;
    QLabel *sgrating2;
    QLabel *pgrating2;
    QLabel *coachrating1;
    QLabel *coachname1;
    QLabel *pgname2;
    QLabel *sgname2;
    QLabel *sfname2;
    QLabel *pfname2;
    QLabel *cname2;
    QLabel *coachname2;
    QLabel *coachrating2;
    QLabel *pgrating2_2;
    QLabel *pgrating2_3;
    QLabel *pgrating2_4;
    QLabel *pgrating2_5;
    QLabel *pgrating2_6;
    QLabel *pgrating2_7;
    QLabel *franchiseName1;
    QLabel *franchiseName2;
    QLabel *city1;
    QLabel *city2;
    QLabel *ovr1;
    QLabel *ovr2;

    void setupUi(QDialog *TeamChoice)
    {
        if (TeamChoice->objectName().isEmpty())
            TeamChoice->setObjectName(QStringLiteral("TeamChoice"));
        TeamChoice->resize(1500, 900);
        TeamChoice->setStyleSheet(QStringLiteral("background: url(:/theme/imageDeFond)"));
        logoTeamChoice = new QLabel(TeamChoice);
        logoTeamChoice->setObjectName(QStringLiteral("logoTeamChoice"));
        logoTeamChoice->setGeometry(QRect(490, 0, 521, 121));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        QBrush brush1(QColor(190, 190, 190, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        logoTeamChoice->setPalette(palette);
        QFont font;
        font.setPointSize(58);
        font.setBold(true);
        font.setWeight(75);
        logoTeamChoice->setFont(font);
        logoTeamChoice->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        listJ1 = new QListWidget(TeamChoice);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        new QListWidgetItem(listJ1);
        listJ1->setObjectName(QStringLiteral("listJ1"));
        listJ1->setGeometry(QRect(50, 260, 200, 581));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        listJ1->setPalette(palette1);
        listJ1->setAutoFillBackground(false);
        J1J2 = new QLabel(TeamChoice);
        J1J2->setObjectName(QStringLiteral("J1J2"));
        J1J2->setGeometry(QRect(630, 110, 251, 71));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        J1J2->setPalette(palette2);
        J1J2->setFont(font);
        J1J2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        logoJ1 = new QLabel(TeamChoice);
        logoJ1->setObjectName(QStringLiteral("logoJ1"));
        logoJ1->setGeometry(QRect(50, 50, 200, 200));
        logoJ1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        logoJ1->setPixmap(QPixmap(QString::fromUtf8(":/franchiselogo/GSW")));
        listJ2 = new QListWidget(TeamChoice);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        new QListWidgetItem(listJ2);
        listJ2->setObjectName(QStringLiteral("listJ2"));
        listJ2->setGeometry(QRect(1250, 260, 200, 581));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        listJ2->setPalette(palette3);
        listJ2->setStyleSheet(QStringLiteral("background-image: url(:/theme/imageDeFond);"));
        logoJ2 = new QLabel(TeamChoice);
        logoJ2->setObjectName(QStringLiteral("logoJ2"));
        logoJ2->setGeometry(QRect(1250, 50, 200, 200));
        logoJ2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        logoJ2->setPixmap(QPixmap(QString::fromUtf8(":/franchiselogo/TOR")));
        playButton = new QPushButton(TeamChoice);
        playButton->setObjectName(QStringLiteral("playButton"));
        playButton->setGeometry(QRect(600, 790, 301, 81));
        QPalette palette4;
        QBrush brush2(QColor(85, 87, 83, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush1);
        playButton->setPalette(palette4);
        QFont font1;
        font1.setPointSize(40);
        playButton->setFont(font1);
        pgname1 = new QLabel(TeamChoice);
        pgname1->setObjectName(QStringLiteral("pgname1"));
        pgname1->setGeometry(QRect(270, 420, 401, 41));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush3(QColor(115, 210, 22, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgname1->setPalette(palette5);
        QFont font2;
        font2.setPointSize(20);
        pgname1->setFont(font2);
        pgname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgname1->setFrameShape(QFrame::NoFrame);
        pgname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sgname1 = new QLabel(TeamChoice);
        sgname1->setObjectName(QStringLiteral("sgname1"));
        sgname1->setEnabled(true);
        sgname1->setGeometry(QRect(270, 470, 401, 41));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sgname1->setPalette(palette6);
        sgname1->setFont(font2);
        sgname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sgname1->setFrameShape(QFrame::NoFrame);
        sgname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sfname1 = new QLabel(TeamChoice);
        sfname1->setObjectName(QStringLiteral("sfname1"));
        sfname1->setEnabled(true);
        sfname1->setGeometry(QRect(270, 520, 401, 41));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sfname1->setPalette(palette7);
        sfname1->setFont(font2);
        sfname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sfname1->setFrameShape(QFrame::NoFrame);
        sfname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pfname1 = new QLabel(TeamChoice);
        pfname1->setObjectName(QStringLiteral("pfname1"));
        pfname1->setEnabled(true);
        pfname1->setGeometry(QRect(270, 570, 401, 41));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pfname1->setPalette(palette8);
        pfname1->setFont(font2);
        pfname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pfname1->setFrameShape(QFrame::NoFrame);
        pfname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cname1 = new QLabel(TeamChoice);
        cname1->setObjectName(QStringLiteral("cname1"));
        cname1->setEnabled(true);
        cname1->setGeometry(QRect(270, 620, 401, 41));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        cname1->setPalette(palette9);
        cname1->setFont(font2);
        cname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        cname1->setFrameShape(QFrame::NoFrame);
        cname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        crating1 = new QLabel(TeamChoice);
        crating1->setObjectName(QStringLiteral("crating1"));
        crating1->setEnabled(true);
        crating1->setGeometry(QRect(680, 620, 31, 41));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        crating1->setPalette(palette10);
        crating1->setFont(font2);
        crating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        crating1->setFrameShape(QFrame::NoFrame);
        crating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pfrating1 = new QLabel(TeamChoice);
        pfrating1->setObjectName(QStringLiteral("pfrating1"));
        pfrating1->setEnabled(true);
        pfrating1->setGeometry(QRect(680, 570, 31, 41));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pfrating1->setPalette(palette11);
        pfrating1->setFont(font2);
        pfrating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pfrating1->setFrameShape(QFrame::NoFrame);
        pfrating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        crating2 = new QLabel(TeamChoice);
        crating2->setObjectName(QStringLiteral("crating2"));
        crating2->setEnabled(true);
        crating2->setGeometry(QRect(790, 620, 31, 41));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        crating2->setPalette(palette12);
        crating2->setFont(font2);
        crating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        crating2->setFrameShape(QFrame::NoFrame);
        crating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sfrating1 = new QLabel(TeamChoice);
        sfrating1->setObjectName(QStringLiteral("sfrating1"));
        sfrating1->setEnabled(true);
        sfrating1->setGeometry(QRect(680, 520, 31, 41));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sfrating1->setPalette(palette13);
        sfrating1->setFont(font2);
        sfrating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sfrating1->setFrameShape(QFrame::NoFrame);
        sfrating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating1 = new QLabel(TeamChoice);
        pgrating1->setObjectName(QStringLiteral("pgrating1"));
        pgrating1->setEnabled(true);
        pgrating1->setGeometry(QRect(680, 420, 31, 41));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating1->setPalette(palette14);
        pgrating1->setFont(font2);
        pgrating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating1->setFrameShape(QFrame::NoFrame);
        pgrating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sgrating1 = new QLabel(TeamChoice);
        sgrating1->setObjectName(QStringLiteral("sgrating1"));
        sgrating1->setEnabled(true);
        sgrating1->setGeometry(QRect(680, 470, 31, 41));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sgrating1->setPalette(palette15);
        sgrating1->setFont(font2);
        sgrating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sgrating1->setFrameShape(QFrame::NoFrame);
        sgrating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pfrating2 = new QLabel(TeamChoice);
        pfrating2->setObjectName(QStringLiteral("pfrating2"));
        pfrating2->setEnabled(true);
        pfrating2->setGeometry(QRect(790, 570, 31, 41));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette16.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pfrating2->setPalette(palette16);
        pfrating2->setFont(font2);
        pfrating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pfrating2->setFrameShape(QFrame::NoFrame);
        pfrating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sfrating2 = new QLabel(TeamChoice);
        sfrating2->setObjectName(QStringLiteral("sfrating2"));
        sfrating2->setEnabled(true);
        sfrating2->setGeometry(QRect(790, 520, 31, 41));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette17.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sfrating2->setPalette(palette17);
        sfrating2->setFont(font2);
        sfrating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sfrating2->setFrameShape(QFrame::NoFrame);
        sfrating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        sgrating2 = new QLabel(TeamChoice);
        sgrating2->setObjectName(QStringLiteral("sgrating2"));
        sgrating2->setEnabled(true);
        sgrating2->setGeometry(QRect(790, 470, 31, 41));
        QPalette palette18;
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette18.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette18.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sgrating2->setPalette(palette18);
        sgrating2->setFont(font2);
        sgrating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sgrating2->setFrameShape(QFrame::NoFrame);
        sgrating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2 = new QLabel(TeamChoice);
        pgrating2->setObjectName(QStringLiteral("pgrating2"));
        pgrating2->setEnabled(true);
        pgrating2->setGeometry(QRect(790, 420, 31, 41));
        QPalette palette19;
        palette19.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette19.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette19.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette19.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette19.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2->setPalette(palette19);
        pgrating2->setFont(font2);
        pgrating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2->setFrameShape(QFrame::NoFrame);
        pgrating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        coachrating1 = new QLabel(TeamChoice);
        coachrating1->setObjectName(QStringLiteral("coachrating1"));
        coachrating1->setEnabled(true);
        coachrating1->setGeometry(QRect(680, 690, 31, 41));
        QPalette palette20;
        palette20.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette20.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette20.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette20.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette20.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        coachrating1->setPalette(palette20);
        coachrating1->setFont(font2);
        coachrating1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        coachrating1->setFrameShape(QFrame::NoFrame);
        coachrating1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        coachname1 = new QLabel(TeamChoice);
        coachname1->setObjectName(QStringLiteral("coachname1"));
        coachname1->setEnabled(true);
        coachname1->setGeometry(QRect(270, 690, 401, 41));
        QPalette palette21;
        palette21.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette21.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette21.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette21.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette21.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        coachname1->setPalette(palette21);
        coachname1->setFont(font2);
        coachname1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        coachname1->setFrameShape(QFrame::NoFrame);
        coachname1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgname2 = new QLabel(TeamChoice);
        pgname2->setObjectName(QStringLiteral("pgname2"));
        pgname2->setGeometry(QRect(830, 420, 401, 41));
        QPalette palette22;
        palette22.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette22.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette22.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette22.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette22.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgname2->setPalette(palette22);
        pgname2->setFont(font2);
        pgname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);background-image: url(:/theme/transparentBackground);"));
        pgname2->setFrameShape(QFrame::NoFrame);
        pgname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        sgname2 = new QLabel(TeamChoice);
        sgname2->setObjectName(QStringLiteral("sgname2"));
        sgname2->setGeometry(QRect(830, 470, 401, 41));
        QPalette palette23;
        palette23.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette23.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette23.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette23.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette23.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sgname2->setPalette(palette23);
        sgname2->setFont(font2);
        sgname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sgname2->setFrameShape(QFrame::NoFrame);
        sgname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        sfname2 = new QLabel(TeamChoice);
        sfname2->setObjectName(QStringLiteral("sfname2"));
        sfname2->setGeometry(QRect(830, 520, 401, 41));
        QPalette palette24;
        palette24.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette24.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette24.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette24.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette24.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        sfname2->setPalette(palette24);
        sfname2->setFont(font2);
        sfname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        sfname2->setFrameShape(QFrame::NoFrame);
        sfname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        pfname2 = new QLabel(TeamChoice);
        pfname2->setObjectName(QStringLiteral("pfname2"));
        pfname2->setGeometry(QRect(830, 570, 401, 41));
        QPalette palette25;
        palette25.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette25.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette25.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette25.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette25.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pfname2->setPalette(palette25);
        pfname2->setFont(font2);
        pfname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pfname2->setFrameShape(QFrame::NoFrame);
        pfname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        cname2 = new QLabel(TeamChoice);
        cname2->setObjectName(QStringLiteral("cname2"));
        cname2->setGeometry(QRect(830, 620, 401, 41));
        QPalette palette26;
        palette26.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette26.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette26.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette26.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette26.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        cname2->setPalette(palette26);
        cname2->setFont(font2);
        cname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        cname2->setFrameShape(QFrame::NoFrame);
        cname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        coachname2 = new QLabel(TeamChoice);
        coachname2->setObjectName(QStringLiteral("coachname2"));
        coachname2->setGeometry(QRect(830, 690, 401, 41));
        QPalette palette27;
        palette27.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette27.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette27.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette27.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette27.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        coachname2->setPalette(palette27);
        coachname2->setFont(font2);
        coachname2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        coachname2->setFrameShape(QFrame::NoFrame);
        coachname2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        coachrating2 = new QLabel(TeamChoice);
        coachrating2->setObjectName(QStringLiteral("coachrating2"));
        coachrating2->setEnabled(true);
        coachrating2->setGeometry(QRect(790, 690, 31, 41));
        QPalette palette28;
        palette28.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette28.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette28.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette28.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette28.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        coachrating2->setPalette(palette28);
        coachrating2->setFont(font2);
        coachrating2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        coachrating2->setFrameShape(QFrame::NoFrame);
        coachrating2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_2 = new QLabel(TeamChoice);
        pgrating2_2->setObjectName(QStringLiteral("pgrating2_2"));
        pgrating2_2->setEnabled(true);
        pgrating2_2->setGeometry(QRect(730, 470, 41, 41));
        QPalette palette29;
        palette29.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette29.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette29.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_2->setPalette(palette29);
        QFont font3;
        font3.setPointSize(36);
        pgrating2_2->setFont(font3);
        pgrating2_2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_2->setFrameShape(QFrame::NoFrame);
        pgrating2_2->setPixmap(QPixmap(QString::fromUtf8(":/postition/pglogo")));
        pgrating2_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_3 = new QLabel(TeamChoice);
        pgrating2_3->setObjectName(QStringLiteral("pgrating2_3"));
        pgrating2_3->setEnabled(true);
        pgrating2_3->setGeometry(QRect(730, 420, 41, 41));
        QPalette palette30;
        palette30.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette30.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette30.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_3->setPalette(palette30);
        pgrating2_3->setFont(font3);
        pgrating2_3->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_3->setFrameShape(QFrame::NoFrame);
        pgrating2_3->setPixmap(QPixmap(QString::fromUtf8(":/postition/sglogo")));
        pgrating2_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_4 = new QLabel(TeamChoice);
        pgrating2_4->setObjectName(QStringLiteral("pgrating2_4"));
        pgrating2_4->setEnabled(true);
        pgrating2_4->setGeometry(QRect(730, 570, 41, 41));
        QPalette palette31;
        palette31.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette31.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette31.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_4->setPalette(palette31);
        pgrating2_4->setFont(font3);
        pgrating2_4->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_4->setFrameShape(QFrame::NoFrame);
        pgrating2_4->setPixmap(QPixmap(QString::fromUtf8(":/postition/sflogo")));
        pgrating2_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_5 = new QLabel(TeamChoice);
        pgrating2_5->setObjectName(QStringLiteral("pgrating2_5"));
        pgrating2_5->setEnabled(true);
        pgrating2_5->setGeometry(QRect(730, 520, 41, 41));
        QPalette palette32;
        palette32.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette32.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette32.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_5->setPalette(palette32);
        pgrating2_5->setFont(font3);
        pgrating2_5->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_5->setFrameShape(QFrame::NoFrame);
        pgrating2_5->setPixmap(QPixmap(QString::fromUtf8(":/postition/pflogo")));
        pgrating2_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_6 = new QLabel(TeamChoice);
        pgrating2_6->setObjectName(QStringLiteral("pgrating2_6"));
        pgrating2_6->setEnabled(true);
        pgrating2_6->setGeometry(QRect(730, 620, 41, 41));
        QPalette palette33;
        palette33.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette33.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette33.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_6->setPalette(palette33);
        pgrating2_6->setFont(font3);
        pgrating2_6->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_6->setFrameShape(QFrame::NoFrame);
        pgrating2_6->setPixmap(QPixmap(QString::fromUtf8(":/postition/clogo")));
        pgrating2_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pgrating2_7 = new QLabel(TeamChoice);
        pgrating2_7->setObjectName(QStringLiteral("pgrating2_7"));
        pgrating2_7->setEnabled(true);
        pgrating2_7->setGeometry(QRect(730, 690, 41, 41));
        QPalette palette34;
        palette34.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette34.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette34.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        pgrating2_7->setPalette(palette34);
        pgrating2_7->setFont(font3);
        pgrating2_7->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        pgrating2_7->setFrameShape(QFrame::NoFrame);
        pgrating2_7->setPixmap(QPixmap(QString::fromUtf8(":/postition/cologo")));
        pgrating2_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        franchiseName1 = new QLabel(TeamChoice);
        franchiseName1->setObjectName(QStringLiteral("franchiseName1"));
        franchiseName1->setGeometry(QRect(270, 330, 441, 61));
        QPalette palette35;
        palette35.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette35.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette35.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette35.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette35.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        franchiseName1->setPalette(palette35);
        QFont font4;
        font4.setPointSize(40);
        font4.setBold(true);
        font4.setWeight(75);
        franchiseName1->setFont(font4);
        franchiseName1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        franchiseName1->setFrameShape(QFrame::NoFrame);
        franchiseName1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        franchiseName2 = new QLabel(TeamChoice);
        franchiseName2->setObjectName(QStringLiteral("franchiseName2"));
        franchiseName2->setGeometry(QRect(790, 330, 441, 61));
        QPalette palette36;
        palette36.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette36.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette36.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette36.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette36.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        franchiseName2->setPalette(palette36);
        franchiseName2->setFont(font4);
        franchiseName2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        franchiseName2->setFrameShape(QFrame::NoFrame);
        franchiseName2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        city1 = new QLabel(TeamChoice);
        city1->setObjectName(QStringLiteral("city1"));
        city1->setGeometry(QRect(270, 300, 441, 41));
        QPalette palette37;
        palette37.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette37.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette37.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette37.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette37.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        city1->setPalette(palette37);
        QFont font5;
        font5.setPointSize(24);
        city1->setFont(font5);
        city1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        city1->setFrameShape(QFrame::NoFrame);
        city1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        city2 = new QLabel(TeamChoice);
        city2->setObjectName(QStringLiteral("city2"));
        city2->setGeometry(QRect(790, 300, 441, 41));
        QPalette palette38;
        palette38.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Active, QPalette::Highlight, brush3);
        palette38.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette38.setBrush(QPalette::Inactive, QPalette::Highlight, brush3);
        palette38.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette38.setBrush(QPalette::Disabled, QPalette::Highlight, brush3);
        city2->setPalette(palette38);
        city2->setFont(font5);
        city2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        city2->setFrameShape(QFrame::NoFrame);
        city2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        ovr1 = new QLabel(TeamChoice);
        ovr1->setObjectName(QStringLiteral("ovr1"));
        ovr1->setGeometry(QRect(540, 260, 171, 41));
        QPalette palette39;
        palette39.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette39.setBrush(QPalette::Active, QPalette::Text, brush);
        palette39.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette39.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette39.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette39.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        ovr1->setPalette(palette39);
        QFont font6;
        font6.setPointSize(30);
        font6.setBold(true);
        font6.setWeight(75);
        ovr1->setFont(font6);
        ovr1->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));
        ovr1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ovr2 = new QLabel(TeamChoice);
        ovr2->setObjectName(QStringLiteral("ovr2"));
        ovr2->setGeometry(QRect(790, 260, 171, 41));
        QPalette palette40;
        palette40.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette40.setBrush(QPalette::Active, QPalette::Text, brush);
        palette40.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette40.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette40.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        palette40.setBrush(QPalette::Disabled, QPalette::Text, brush1);
        ovr2->setPalette(palette40);
        ovr2->setFont(font6);
        ovr2->setStyleSheet(QStringLiteral("background-image: url(:/theme/transparentBackground);"));

        retranslateUi(TeamChoice);

        QMetaObject::connectSlotsByName(TeamChoice);
    } // setupUi

    void retranslateUi(QDialog *TeamChoice)
    {
        TeamChoice->setWindowTitle(QApplication::translate("TeamChoice", "LO43 Shot - Team Choice", Q_NULLPTR));
        logoTeamChoice->setText(QApplication::translate("TeamChoice", "TEAM CHOICE", Q_NULLPTR));

        const bool __sortingEnabled = listJ1->isSortingEnabled();
        listJ1->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem = listJ1->item(0);
        ___qlistwidgetitem->setText(QApplication::translate("TeamChoice", "Atlanta Hawks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem1 = listJ1->item(1);
        ___qlistwidgetitem1->setText(QApplication::translate("TeamChoice", "Brooklyn Nets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem2 = listJ1->item(2);
        ___qlistwidgetitem2->setText(QApplication::translate("TeamChoice", "Boston Celtics", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem3 = listJ1->item(3);
        ___qlistwidgetitem3->setText(QApplication::translate("TeamChoice", "Charlotte Hornets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem4 = listJ1->item(4);
        ___qlistwidgetitem4->setText(QApplication::translate("TeamChoice", "Chicago Bulls", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem5 = listJ1->item(5);
        ___qlistwidgetitem5->setText(QApplication::translate("TeamChoice", "Cleveland Cavaliers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem6 = listJ1->item(6);
        ___qlistwidgetitem6->setText(QApplication::translate("TeamChoice", "Dallas Mavericks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem7 = listJ1->item(7);
        ___qlistwidgetitem7->setText(QApplication::translate("TeamChoice", "Denver Nuggets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem8 = listJ1->item(8);
        ___qlistwidgetitem8->setText(QApplication::translate("TeamChoice", "Detroit Pistons", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem9 = listJ1->item(9);
        ___qlistwidgetitem9->setText(QApplication::translate("TeamChoice", "Golden State Warriors", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem10 = listJ1->item(10);
        ___qlistwidgetitem10->setText(QApplication::translate("TeamChoice", "Houston Rockets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem11 = listJ1->item(11);
        ___qlistwidgetitem11->setText(QApplication::translate("TeamChoice", "Indiana Pacers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem12 = listJ1->item(12);
        ___qlistwidgetitem12->setText(QApplication::translate("TeamChoice", "Los Angeles Clippers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem13 = listJ1->item(13);
        ___qlistwidgetitem13->setText(QApplication::translate("TeamChoice", "Los Angeles Lakers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem14 = listJ1->item(14);
        ___qlistwidgetitem14->setText(QApplication::translate("TeamChoice", "Memphis Grizzlies", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem15 = listJ1->item(15);
        ___qlistwidgetitem15->setText(QApplication::translate("TeamChoice", "Miami Heat", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem16 = listJ1->item(16);
        ___qlistwidgetitem16->setText(QApplication::translate("TeamChoice", "Milwaukee Bucks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem17 = listJ1->item(17);
        ___qlistwidgetitem17->setText(QApplication::translate("TeamChoice", "Minnesota Timberwolves", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem18 = listJ1->item(18);
        ___qlistwidgetitem18->setText(QApplication::translate("TeamChoice", "New Orleans Pelicans", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem19 = listJ1->item(19);
        ___qlistwidgetitem19->setText(QApplication::translate("TeamChoice", "New York Knicks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem20 = listJ1->item(20);
        ___qlistwidgetitem20->setText(QApplication::translate("TeamChoice", "Oklahoma City Thunder", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem21 = listJ1->item(21);
        ___qlistwidgetitem21->setText(QApplication::translate("TeamChoice", "Orlando Magic", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem22 = listJ1->item(22);
        ___qlistwidgetitem22->setText(QApplication::translate("TeamChoice", "Philadelphia 76ers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem23 = listJ1->item(23);
        ___qlistwidgetitem23->setText(QApplication::translate("TeamChoice", "Phoenix Suns", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem24 = listJ1->item(24);
        ___qlistwidgetitem24->setText(QApplication::translate("TeamChoice", "Portland Trail Blazers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem25 = listJ1->item(25);
        ___qlistwidgetitem25->setText(QApplication::translate("TeamChoice", "Sacramento Kings", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem26 = listJ1->item(26);
        ___qlistwidgetitem26->setText(QApplication::translate("TeamChoice", "San Antonio Spurs", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem27 = listJ1->item(27);
        ___qlistwidgetitem27->setText(QApplication::translate("TeamChoice", "Toronto Raptors", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem28 = listJ1->item(28);
        ___qlistwidgetitem28->setText(QApplication::translate("TeamChoice", "Utah Jazz", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem29 = listJ1->item(29);
        ___qlistwidgetitem29->setText(QApplication::translate("TeamChoice", "Washington Wizards", Q_NULLPTR));
        listJ1->setSortingEnabled(__sortingEnabled);

        J1J2->setText(QApplication::translate("TeamChoice", "J1 -  J2", Q_NULLPTR));
        logoJ1->setText(QString());

        const bool __sortingEnabled1 = listJ2->isSortingEnabled();
        listJ2->setSortingEnabled(false);
        QListWidgetItem *___qlistwidgetitem30 = listJ2->item(0);
        ___qlistwidgetitem30->setText(QApplication::translate("TeamChoice", "Atlanta Hawks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem31 = listJ2->item(1);
        ___qlistwidgetitem31->setText(QApplication::translate("TeamChoice", "Brooklyn Nets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem32 = listJ2->item(2);
        ___qlistwidgetitem32->setText(QApplication::translate("TeamChoice", "Boston Celtics", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem33 = listJ2->item(3);
        ___qlistwidgetitem33->setText(QApplication::translate("TeamChoice", "Charlotte Hornets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem34 = listJ2->item(4);
        ___qlistwidgetitem34->setText(QApplication::translate("TeamChoice", "Chicago Bulls", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem35 = listJ2->item(5);
        ___qlistwidgetitem35->setText(QApplication::translate("TeamChoice", "Cleveland Cavaliers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem36 = listJ2->item(6);
        ___qlistwidgetitem36->setText(QApplication::translate("TeamChoice", "Dallas Mavericks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem37 = listJ2->item(7);
        ___qlistwidgetitem37->setText(QApplication::translate("TeamChoice", "Denver Nuggets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem38 = listJ2->item(8);
        ___qlistwidgetitem38->setText(QApplication::translate("TeamChoice", "Detroit Pistons", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem39 = listJ2->item(9);
        ___qlistwidgetitem39->setText(QApplication::translate("TeamChoice", "Golden State Warriors", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem40 = listJ2->item(10);
        ___qlistwidgetitem40->setText(QApplication::translate("TeamChoice", "Houston Rockets", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem41 = listJ2->item(11);
        ___qlistwidgetitem41->setText(QApplication::translate("TeamChoice", "Indiana Pacers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem42 = listJ2->item(12);
        ___qlistwidgetitem42->setText(QApplication::translate("TeamChoice", "Los Angeles Clippers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem43 = listJ2->item(13);
        ___qlistwidgetitem43->setText(QApplication::translate("TeamChoice", "Los Angeles Lakers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem44 = listJ2->item(14);
        ___qlistwidgetitem44->setText(QApplication::translate("TeamChoice", "Memphis Grizzlies", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem45 = listJ2->item(15);
        ___qlistwidgetitem45->setText(QApplication::translate("TeamChoice", "Miami Heat", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem46 = listJ2->item(16);
        ___qlistwidgetitem46->setText(QApplication::translate("TeamChoice", "Milwaukee Bucks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem47 = listJ2->item(17);
        ___qlistwidgetitem47->setText(QApplication::translate("TeamChoice", "Minnesota Timberwolves", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem48 = listJ2->item(18);
        ___qlistwidgetitem48->setText(QApplication::translate("TeamChoice", "New Orleans Pelicans", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem49 = listJ2->item(19);
        ___qlistwidgetitem49->setText(QApplication::translate("TeamChoice", "New York Knicks", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem50 = listJ2->item(20);
        ___qlistwidgetitem50->setText(QApplication::translate("TeamChoice", "Oklahoma City Thunder", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem51 = listJ2->item(21);
        ___qlistwidgetitem51->setText(QApplication::translate("TeamChoice", "Orlando Magic", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem52 = listJ2->item(22);
        ___qlistwidgetitem52->setText(QApplication::translate("TeamChoice", "Philadelphia 76ers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem53 = listJ2->item(23);
        ___qlistwidgetitem53->setText(QApplication::translate("TeamChoice", "Phoenix Suns", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem54 = listJ2->item(24);
        ___qlistwidgetitem54->setText(QApplication::translate("TeamChoice", "Portland Trail Blazers", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem55 = listJ2->item(25);
        ___qlistwidgetitem55->setText(QApplication::translate("TeamChoice", "Sacramento Kings", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem56 = listJ2->item(26);
        ___qlistwidgetitem56->setText(QApplication::translate("TeamChoice", "San Antonio Spurs", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem57 = listJ2->item(27);
        ___qlistwidgetitem57->setText(QApplication::translate("TeamChoice", "Toronto Raptors", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem58 = listJ2->item(28);
        ___qlistwidgetitem58->setText(QApplication::translate("TeamChoice", "Utah Jazz", Q_NULLPTR));
        QListWidgetItem *___qlistwidgetitem59 = listJ2->item(29);
        ___qlistwidgetitem59->setText(QApplication::translate("TeamChoice", "Washington Wizards", Q_NULLPTR));
        listJ2->setSortingEnabled(__sortingEnabled1);

        logoJ2->setText(QString());
        playButton->setText(QApplication::translate("TeamChoice", "PLAY", Q_NULLPTR));
        pgname1->setText(QApplication::translate("TeamChoice", "Stephen Curry", Q_NULLPTR));
        sgname1->setText(QApplication::translate("TeamChoice", "Klay Thompson", Q_NULLPTR));
        sfname1->setText(QApplication::translate("TeamChoice", "Kevin Durant", Q_NULLPTR));
        pfname1->setText(QApplication::translate("TeamChoice", "Draymond Green", Q_NULLPTR));
        cname1->setText(QApplication::translate("TeamChoice", "DeMarcus Cousins", Q_NULLPTR));
        crating1->setText(QApplication::translate("TeamChoice", "90", Q_NULLPTR));
        pfrating1->setText(QApplication::translate("TeamChoice", "87", Q_NULLPTR));
        crating2->setText(QApplication::translate("TeamChoice", "82", Q_NULLPTR));
        sfrating1->setText(QApplication::translate("TeamChoice", "97", Q_NULLPTR));
        pgrating1->setText(QApplication::translate("TeamChoice", "95", Q_NULLPTR));
        sgrating1->setText(QApplication::translate("TeamChoice", "89", Q_NULLPTR));
        pfrating2->setText(QApplication::translate("TeamChoice", "79", Q_NULLPTR));
        sfrating2->setText(QApplication::translate("TeamChoice", "94", Q_NULLPTR));
        sgrating2->setText(QApplication::translate("TeamChoice", "75", Q_NULLPTR));
        pgrating2->setText(QApplication::translate("TeamChoice", "85", Q_NULLPTR));
        coachrating1->setText(QApplication::translate("TeamChoice", "94", Q_NULLPTR));
        coachname1->setText(QApplication::translate("TeamChoice", "Steve Kerr", Q_NULLPTR));
        pgname2->setText(QApplication::translate("TeamChoice", "Kyle Lowry", Q_NULLPTR));
        sgname2->setText(QApplication::translate("TeamChoice", "Danny Green", Q_NULLPTR));
        sfname2->setText(QApplication::translate("TeamChoice", "Kawhi Leonard", Q_NULLPTR));
        pfname2->setText(QApplication::translate("TeamChoice", "Serge Ibaka", Q_NULLPTR));
        cname2->setText(QApplication::translate("TeamChoice", "Jonas Valanciunas", Q_NULLPTR));
        coachname2->setText(QApplication::translate("TeamChoice", "Nick Nurse", Q_NULLPTR));
        coachrating2->setText(QApplication::translate("TeamChoice", "93", Q_NULLPTR));
        pgrating2_2->setText(QString());
        pgrating2_3->setText(QString());
        pgrating2_4->setText(QString());
        pgrating2_5->setText(QString());
        pgrating2_6->setText(QString());
        pgrating2_7->setText(QString());
        franchiseName1->setText(QApplication::translate("TeamChoice", "Warriors", Q_NULLPTR));
        franchiseName2->setText(QApplication::translate("TeamChoice", "Raptors", Q_NULLPTR));
        city1->setText(QApplication::translate("TeamChoice", "GoldenState", Q_NULLPTR));
        city2->setText(QApplication::translate("TeamChoice", "Toronto", Q_NULLPTR));
        ovr1->setText(QApplication::translate("TeamChoice", "92", Q_NULLPTR));
        ovr2->setText(QApplication::translate("TeamChoice", "83", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class TeamChoice: public Ui_TeamChoice {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TEAMCHOICE_H
